import {footerBrand as brand} from '../shared/brand.mjs';
import {company} from '../../constants/content.mjs';
import {services} from '../../constants/content.mjs';
import {icon} from '../ui/icon.mjs';
import {navigation} from '../../constants/navigation.mjs';
export function footer(){return `<footer class="site-footer">
<div class="footer-contact"><div class="container"><a href="tel:${company.tel}">${icon('phone')}<span><small>Call our team</small>${company.phone}</span></a><a href="mailto:${company.email}">${icon('mail')}<span><small>Email</small>${company.email}</span></a><div>${icon('pin')}<span><small>Our offices</small>Perth & Melbourne, Australia</span></div></div></div>
<div class="footer-body"><img class="footer-plane" src="/brand/footer-airplane-reference.png" width="276" height="276" alt="" aria-hidden="true" decoding="async">
<div class="container footer-main"><div class="footer-brand-panel">${brand()}<p>Personalized, professional and transparent visa support for students, professionals and families.</p><a class="footer-contact-link" href="/contact/">Request an eligibility assessment <span aria-hidden="true">↗</span></a><div class="footer-ornament" aria-hidden="true"><span></span><i></i><b></b></div></div><div><h3>Explore</h3>${navigation.slice(1).map(([n,u])=>`<a href="${u}">${n}</a>`).join('')}</div><div><h3>Our services</h3>${services.filter((_,i)=>[0,3,5,6].includes(i)).map(s=>`<a href="/services/${s.slug}/">${s.name}</a>`).join('')}<a href="/coaching/ielts/">IELTS Coaching</a><a href="/coaching/pte/">PTE Coaching</a></div><div class="footer-offices"><h3>Visit our offices</h3><p>${company.offices[0]}</p><p>${company.offices[1]}</p><p>${company.hours}</p><a class="footer-visit" href="/contact/">Contact before visiting <span aria-hidden="true">↗</span></a></div></div></div>
<div class="footer-legal"><div class="container"><span>© ${new Date().getFullYear()} Migration Factor</span><a href="https://www.bshsolutionss.com/">Powered by BSH Solutions</a></div></div></footer><a class="back-top" href="#top" aria-label="Back to top">↑</a>`}
