import {company,services,coaching} from '../constants/content.mjs';
import * as ui from '../components/index.mjs';
const {hero,features,about,process:processSection,enquiry,countrySection,coachingSection,cta,articles,breadcrumb,button,title,form,faqSection,serviceGrid,icon,photo}=ui;
const pages=[];
function add(path,name,description,body,extra={}){pages.push({path,name,description,body,...extra})}
add('/','Visa & Migration Consultancy', 'Migration Factor supports students, professionals and families with migration and visa guidance. Explore services, IELTS/PTE coaching and contact our team.',hero()+features()+about()+processSection()+enquiry()+countrySection()+coachingSection()+cta()+articles());
add('/about/','About Migration Factor','Learn about Migration Factor, a Perth-based migration and visa consultancy supporting students, professionals and families.',breadcrumb('About Migration Factor','Personalized, professional and transparent visa support.')+about()+`<section class="section soft"><div class="container values-grid"><article>${title('OUR MISSION','Guidance with purpose.',false)}<p>${company.mission}</p></article><article>${title('OUR VISION','New beginnings <br>beyond borders.',false)}<p>${company.vision}</p></article></div><div class="container origin-note">Supporting clients from Pakistan, India, Bangladesh, Sri Lanka and Nepal.</div></section>`+processSection()+cta());
add('/services/','Visa & Immigration Services','Explore Migration Factor student, visitor, partner, parent, skilled, employer-sponsored, citizenship, business, protection and review services.',breadcrumb('Visa & immigration services','Support for studying, working, living and bringing family together.')+`<section class="section"><div class="container">${serviceGrid()}</div></section>`+processSection()+cta());
for(const s of services){add(`/services/${s.slug}/`,s.name,`${s.name} support from Migration Factor. ${s.description}`,breadcrumb(s.name,s.group)+`<section class="section"><div class="container detail-layout"><article><span class="service-icon">${icon(s.icon)}</span><h2>${s.name} support</h2><p class="lead">${s.description}</p><h3>Start with your circumstances</h3><p>Prepare your basic profile: passport, age, education, work history, English result, family details and current visa status. Request an eligibility assessment and a document checklist.</p><h3>Understand your next steps</h3><p>Ask for your potential pathway, estimated timeline, professional fee and government charges in writing and separately.</p><p class="source-note">Service summary based on the company report. Current requirements and availability should be confirmed with an appropriately registered migration professional.</p>${button('Discuss this service',`/contact/?service=${encodeURIComponent(s.name)}`)}</article><aside class="service-sidebar"><h3>Explore our services</h3>${services.map(x=>`<a href="/services/${x.slug}/" ${x.slug===s.slug?'aria-current="page"':''}>${x.name}</a>`).join('')}<a class="sidebar-phone" href="tel:${company.tel}">${icon('phone')}${company.phone}</a></aside></div></section>`+processSection())}
add('/countries/','Countries & Destinations','Explore destinations mentioned by Migration Factor: Australia, United Kingdom, Canada, United States, New Zealand and Europe.',breadcrumb('Countries & destinations','Discuss where you want your journey to take you.')+countrySection()+cta());
add('/faq/','Frequently Asked Questions','Find answers about Migration Factor services, the eligibility assessment process, preparing documents, coaching and contacting our team.',breadcrumb('Frequently asked questions')+faqSection(),{faq:true});
add('/contact/','Contact Migration Factor','Contact Migration Factor at +61 426 122 786 or info@migrationfactor.com. Offices listed in Mirrabooka, Perth and Cranbourne, Melbourne.',breadcrumb('Let’s talk about your future','Start with your goals. We’ll help you explore your next steps.')+`<section class="section"><div class="container contact-grid"><div>${title('CONTACT MIGRATION FACTOR','A conversation is <br>your first step.',false)}<div class="contact-item">${icon('phone')}<div><h3>Call our team</h3><a href="tel:${company.tel}">${company.phone}</a></div></div><div class="contact-item">${icon('mail')}<div><h3>Email us</h3><a href="mailto:${company.email}">${company.email}</a></div></div>${company.offices.map((o,i)=>`<div class="contact-item">${icon('pin')}<div><h3>${i===0?'Perth':'Melbourne'} office</h3><p>${o}</p></div></div>`).join('')}<p>${company.hours}. Contact the team before visiting.</p></div>${form('contact')}</div></section>`);
for(const c of coaching){add(`/coaching/${c.slug}/`,c.name,`${c.name} with Migration Factor. ${c.text}`,breadcrumb(c.name,'English language preparation')+`<section class="section"><div class="container detail-layout"><article><span class="service-icon">${icon(c.icon)}</span><h2>Prepare with ${c.name.split(' ')[0]}</h2><p class="lead">${c.text}</p><ul class="checks">${c.items.map(x=>`<li>${x}</li>`).join('')}</ul><p>Check the official English test requirements of your institution and visa pathway before choosing your test.</p>${button('Enquire about coaching',`/contact/?service=${encodeURIComponent(c.name)}`)}</article><aside class="coaching-aside">${photo('enquiry')}<h3>Online classes. <br>Personalized preparation.</h3></aside></div></section>`+coachingSection())}
add('/guides/preparing-your-profile/','Preparing Your Profile','Prepare your goals and basic profile before requesting a Migration Factor eligibility assessment.',breadcrumb('Preparing your profile','Practical next steps')+`<section class="section"><article class="container narrow prose"><h2>Start with your objective</h2><p>Clarify whether your objective is study, work, partner, parent, visitor, business or protection.</p><h2>Prepare your basic profile</h2><ul><li>Passport and age</li><li>Education and work history</li><li>English result</li><li>Family details</li><li>Current visa status</li></ul><h2>Request an eligibility assessment</h2><p>Ask for the pathway, estimated timeline, professional fee and government charges in writing and separately.</p>${button('Request an eligibility assessment')}</article></section>`);
add('/guides/document-checklist/','Your Document Checklist','Plan your document checklist and review your application details with Migration Factor.',breadcrumb('Your document checklist','Practical next steps')+`<section class="section"><article class="container narrow prose"><h2>Ask for a checklist</h2><p>Obtain a document checklist and confirm validity, translations, certification and evidence requirements.</p><h2>Review before lodgement</h2><p>Read and verify all forms, statements, financial evidence and personal details before lodgement.</p><h2>Confirm claims and deadlines</h2><p>Cross-check success-rate, guaranteed-approval or fast-outcome claims against official rules and signed engagement terms. If you have received a refusal or cancellation, check the deadline immediately and contact a registered professional without delay.</p>${button('Discuss your documents')}</article></section>`);
add('/404/','Page not found','This Migration Factor page could not be found.',breadcrumb('Page not found','The page may have moved. Explore our services or return home.')+`<section class="section center">${button('Return home','/')}</section>`,{noindex:true});

export {pages};
